from tkinter import *
from tkinter import messagebox
w=Tk()
w.title('APPLICATION FORM')
w.iconbitmap('menu.ico')
w.geometry('500x500')
bgimg=PhotoImage(file='appbg.ppm')
lbimg=Label(w,image=bgimg).pack()
font1=("Comic Sans MS",15,"bold")
label1=Label(w,text='VERIFY YOUR EMAIL',font=font1)
label1.place(relx=0.3,rely=0.1)
v=IntVar()
rb1=Radiobutton(w,text='MALE',variable=v,value=1,bd=6).place(relx=0.4,rely=0.5)
rb2=Radiobutton(w,text='FEMALE',variable=v,value=2,bd=6).place(relx=0.4,rely=0.6)
def clicklog():
     button['state']='disabled'
     button['bg']='white'
     messagebox.showinfo("INFORMATION WINDOW","YOU WILL BE SUCCESSFULLY LOGGED OUT")
     labt=Label(w,text='YOU ARE SUCESSFULLY LOGGED OUT!!',font=font1,background='#FFE633',foreground='black')
     labt.place(relx=0.1,rely=0.2)
button1=Button(w,width=8,height=2,text='LOG OUT',fg='black',bd=8,command=clicklog)
button1.place(relx=0.9,rely=0.1,anchor=CENTER)
font2=("Arial",10,"bold")
label2=Label(w,text='ENTER NAME:',foreground='black',font=font2)
label2.place(relx=0.1,rely=0.3)
e1=Entry(w,width=30,bg='#33FFF3',fg='black',bd=6).place(relx=0.3,rely=0.3)
label3=Label(w,text='ENTER E-MAIL:',font=font2,foreground='black')
label3.place(relx=0.1,rely=0.4)
e2=Entry(w,width=30,bg='#33FFF3',foreground='black',bd=6).place(relx=0.3,rely=0.4)
label4=Label(w,text='SELECT:',font=font2,foreground='black')
label4.place(relx=0.2,rely=0.5)
label5=Label(w,text='PHONE NO:',font=font2,foreground='black')
label5.place(relx=0.1,rely=0.7)
e3=Entry(w,width=30,bg='#33FF8D',fg='black',bd=6).place(relx=0.3,rely=0.7)
font3=("Lorem ipsum dolor sit amet",10,'bold')
def click():
     button['state']='disabled'
     button['text']='DONE'
     button['bg']='white'
     messagebox.showinfo("INFORMATION WINDOW","CONGRTAULATIONS,YOU HAVE SUCESSFULLY SIGNED IN!!!")
     lab=Label(w,text='THANK YOU!!!',font=font3,width=10)
     lab.place(relx=0.4,rely=0.9)
button=Button(w,width=8,height=2,text='SIGN IN',font=font3,background='#FFD733',foreground='black',command=click,bd=6)
button.place(relx=0.4,rely=0.8)
menu=Menu(w)
w.config(menu=menu)
filemenu=Menu(menu)
menu.add_cascade(label='File',menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open...')
filemenu.add_separator()
filemenu.add_command(label='Exit')
helpmenu=Menu(menu)
menu.add_cascade(label='Help',menu=helpmenu)
helpmenu.add_command(label='About')
mainloop()